# Generated by Django 5.1.5 on 2025-01-19 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao_cotacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitacaoCatacao',
            new_name='SolicitacaoCotacao',
        ),
    ]
