# Generated by Django 5.1.5 on 2025-01-20 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('solicitacao_cotacao', '0002_rename_solicitacaocatacao_solicitacaocotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contrato', models.DateTimeField(auto_now_add=True)),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especificacoes_tecnicas', models.TextField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao_cotacao.solicitacaocotacao')),
            ],
        ),
    ]
