# Generated by Django 5.1.5 on 2025-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='anexo',
            field=models.FileField(default=1, upload_to='contratos'),
            preserve_default=False,
        ),
    ]
