# Generated by Django 5.1.5 on 2025-01-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_contrato_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='contratos'),
        ),
    ]
