# Generated by Django 5.1.5 on 2025-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contrato_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
